---
name: Build release zip

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'plus-v*'

jobs:
  compile_launcher:
    uses: ./.github/workflows/_compile_launcher.yml

  build-release-zip:
    name: Build release zip
    needs: compile_launcher
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we want to collect tag info, so clone all history

      - name: Download exe
        uses: actions/download-artifact@v8
        with:
          name: dqxclarity.exe

      - name: Update GITHUB_ENV env
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:8}" >> "$GITHUB_ENV"
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            [[ "$GITHUB_REF_NAME" =~ ^plus-v[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit 1
            [[ "${GITHUB_REF_NAME#plus-v}" == "$(tr -d '\r\n' < version.update)" ]] || exit 1
          fi

      - name: Build package
        run: |
          rsync -av --exclude="imgs/" --exclude="launcher/" --exclude="tests/" app/* dqxclarity/;
          cp version.update pyproject.toml dqxclarity.exe dqxclarity/;
          cp user_settings.example.ini dqxclarity/user_settings.ini;
          cp clarity_dialog.db dqxclarity/misc_files;

      - name: Zip package (pre-release)
        if: github.ref_type != 'tag'
        run: zip -r dqxclarity-dev-$SHORT_SHA.zip dqxclarity

      - name: Zip package (release)
        if: github.ref_type == 'tag'
        run: zip -r dqxclarity.zip dqxclarity

      - name: Cleanup existing assets from dev release
        if: github.ref_type != 'tag'
        uses: mknejp/delete-release-assets@v1
        continue-on-error: true  # tag or assets may not exist
        with:
          token: ${{ github.token }}
          tag: plus-dev
          assets: '*.zip'

      - name: Create dev release
        if: github.ref_type != 'tag'
        uses: softprops/action-gh-release@v3
        with:
          files: dqxclarity-dev-${{ env.SHORT_SHA }}.zip
          prerelease: true
          tag_name: plus-dev
          name: 'dqxclarity Plus development build'
          body: "This is a pre-release build! You don't want to download this!"

      - name: Create prod release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          files: dqxclarity.zip
          prerelease: false
          draft: false
          tag_name: ${{ github.ref_name }}
          name: 'dqxclarity Plus ${{ github.ref_name }}'
          generate_release_notes: true
          fail_on_unmatched_files: true
