---
name: Build release zip

permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  compile_launcher:
    uses: ./.github/workflows/_compile_launcher.yml

  build-release-zip:
    name: Build release zip
    needs: compile_launcher
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we want to collect tag info, so clone all history

      - name: Download exe
        uses: actions/download-artifact@v8
        with:
          name: dqxclarity.exe

      - name: Update GITHUB_ENV env
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "CURRENT_TAG=`git describe --always --tags $(git rev-list --tags) | grep -v 'dev' | grep -E '^v' | head -n1 | cut -d"-" -f1`" >> $GITHUB_ENV

      - name: Build package
        run: |
          rsync -av --exclude="imgs/" --exclude="launcher/" --exclude="tests/" app/* dqxclarity/;
          cp version.update pyproject.toml dqxclarity.exe dqxclarity/;
          cp user_settings.example.ini dqxclarity/user_settings.ini;
          cp clarity_dialog.db dqxclarity/misc_files;

      - name: Zip package (pre-release)
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: zip -r dqxclarity-dev-$SHORT_SHA.zip dqxclarity

      - name: Zip package (release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: zip -r dqxclarity.zip dqxclarity

      - name: Cleanup existing assets from dev release
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: mknejp/delete-release-assets@v1
        continue-on-error: true  # tag or assets may not exist
        with:
          token: ${{ github.token }}
          tag: ${{ env.CURRENT_TAG }}-dev
          assets: '*.zip'

      - name: Create dev release
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: softprops/action-gh-release@v3
        with:
          files: dqxclarity-dev-${{ env.SHORT_SHA }}.zip
          prerelease: true
          tag_name: ${{ env.CURRENT_TAG }}-dev
          name: 'Dev Build: ${{ env.CURRENT_TAG }}-dev'
          body: "This is a pre-release build! You don't want to download this!"

      - name: Create prod release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v3
        with:
          files: dqxclarity.zip
          prerelease: false
          draft: false
          tag_name: ${{ github.ref_name }}
          name: 'dqxclarity multilingual ${{ github.ref_name }}'
          generate_release_notes: true
          fail_on_unmatched_files: true
