---
name: Python unit tests

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  unit_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install .

      - name: Run unit tests
        run: |
          cd app
          python -m unittest discover -s tests

  launcher_core_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Run launcher core tests
        run: dotnet run --project launcher.tests/DqxClarity.Launcher.CoreTests.csproj --configuration Release
